% Generated by MATLAB(R) 24.2 (R2024b) and 5G Toolbox 24.2 (R2024b).
% Generated on: 04-Dec-2024 16:40:50

%% Generating Downlink waveform
% Downlink configuration
cfgDL = nrDLCarrierConfig;
cfgDL.Label = 'Carrier1';
cfgDL.FrequencyRange = 'FR1';
cfgDL.ChannelBandwidth = 50;
cfgDL.NCellID = 1;
cfgDL.NumSubframes = 10;
cfgDL.InitialNSubframe = 0;
cfgDL.WindowingPercent = 0;
cfgDL.SampleRate = [];
cfgDL.CarrierFrequency = 0;

%% SCS specific carriers
scscarrier = nrSCSCarrierConfig;
scscarrier.SubcarrierSpacing = 15;
scscarrier.NSizeGrid = 270;
scscarrier.NStartGrid = 3;

cfgDL.SCSCarriers = {scscarrier};

%% Bandwidth Parts
bwp = nrWavegenBWPConfig;
bwp.BandwidthPartID = 1;
bwp.Label = 'BWP1';
bwp.SubcarrierSpacing = 15;
bwp.CyclicPrefix = 'normal';
bwp.NSizeBWP = 270;
bwp.NStartBWP = 3;

cfgDL.BandwidthParts = {bwp};

%% Synchronization Signals Burst
ssburst = nrWavegenSSBurstConfig;
ssburst.Enable = true;
ssburst.Power = 0;
ssburst.BlockPattern = 'Case A';
ssburst.TransmittedBlocks = ones([1 4]);
ssburst.Period = 20;
ssburst.NCRBSSB = [];
ssburst.KSSB = 0;
ssburst.DataSource = 'MIB';
ssburst.DMRSTypeAPosition = 2;
ssburst.CellBarred = false;
ssburst.IntraFreqReselection = false;
ssburst.PDCCHConfigSIB1 = 0;
ssburst.SubcarrierSpacingCommon = 15;

cfgDL.SSBurst = ssburst;

%% CORESET and Search Space Configuration
% CORESET 1
coreset1 = nrCORESETConfig;
coreset1.CORESETID = 0;
coreset1.Label = 'CORESET0';
coreset1.FrequencyResources = ones([1 8]);
coreset1.Duration = 2;
coreset1.CCEREGMapping = 'interleaved';
coreset1.REGBundleSize = 6;
coreset1.InterleaverSize = 2;
coreset1.ShiftIndex = 0;
coreset1.PrecoderGranularity = 'sameAsREG-bundle';
coreset1.RBOffset = [];

% CORESET 2
coreset2 = nrCORESETConfig;
coreset2.CORESETID = 1;
coreset2.Label = 'CORESET1';
coreset2.FrequencyResources = ones([1 8]);
coreset2.Duration = 2;
coreset2.CCEREGMapping = 'interleaved';
coreset2.REGBundleSize = 6;
coreset2.InterleaverSize = 2;
coreset2.ShiftIndex = 0;
coreset2.PrecoderGranularity = 'sameAsREG-bundle';
coreset2.RBOffset = [];

cfgDL.CORESET = {coreset1,coreset2};

% Search Spaces
searchspace = nrSearchSpaceConfig;
searchspace.SearchSpaceID = 1;
searchspace.Label = 'SearchSpace1';
searchspace.CORESETID = 1;
searchspace.SearchSpaceType = 'ue';
searchspace.StartSymbolWithinSlot = 0;
searchspace.SlotPeriodAndOffset = [1 0];
searchspace.Duration = 1;
searchspace.NumCandidates = [8 8 4 2 1];

cfgDL.SearchSpaces = {searchspace};

%% PDCCH Instances Configuration
pdcch = nrWavegenPDCCHConfig;
pdcch.Enable = true;
pdcch.Label = 'PDCCH1';
pdcch.Power = 0;
pdcch.BandwidthPartID = 1;
pdcch.SearchSpaceID = 1;
pdcch.AggregationLevel = 8;
pdcch.AllocatedCandidate = 1;
pdcch.CCEOffset = [];
pdcch.SlotAllocation = 0;
pdcch.Period = 1;
pdcch.Coding = true;
pdcch.DataBlockSize = 20;
pdcch.DataSource = 'PN9-ITU';
pdcch.RNTI = 1;
pdcch.DMRSScramblingID = 2;
pdcch.DMRSPower = 0;

cfgDL.PDCCH = {pdcch};

%% PDSCH Instances Configuration
pdsch = nrWavegenPDSCHConfig;
pdsch.Enable = true;
pdsch.Label = 'PDSCH1';
pdsch.Power = 0;
pdsch.BandwidthPartID = 1;
pdsch.Modulation = 'QPSK';
pdsch.NumLayers = 1;
pdsch.MappingType = 'A';
pdsch.ReservedCORESET = [];
pdsch.SymbolAllocation = [0 14];
pdsch.SlotAllocation = 0:9;
pdsch.Period = 10;
pdsch.PRBSet = 0:269;
pdsch.PRBSetType = 'VRB';
pdsch.VRBToPRBInterleaving = false;
pdsch.VRBBundleSize = 2;
pdsch.NID = [];
pdsch.RNTI = 1;
pdsch.Coding = true;
pdsch.TargetCodeRate = 0.513671875;
pdsch.TBScaling = 1;
pdsch.XOverhead = 0;
pdsch.LimitedBufferRateMatching = true;
pdsch.MaxNumLayers = 8;
pdsch.MCSTable = 'qam256';
pdsch.RVSequence = [0 2 3 1];
pdsch.DataSource = 'PN9-ITU';
pdsch.DMRSPower = 0;
pdsch.EnablePTRS = false;
pdsch.PTRSPower = 0;

% PDSCH Reserved PRB
pdschReservedPRB = nrPDSCHReservedConfig;
pdschReservedPRB.PRBSet = [];
pdschReservedPRB.SymbolSet = [];
pdschReservedPRB.Period = [];

pdsch.ReservedPRB = {pdschReservedPRB};

% PDSCH DM-RS
pdschDMRS = nrPDSCHDMRSConfig;
pdschDMRS.DMRSConfigurationType = 1;
pdschDMRS.DMRSReferencePoint = 'CRB0';
pdschDMRS.DMRSTypeAPosition = 2;
pdschDMRS.DMRSAdditionalPosition = 0;
pdschDMRS.DMRSLength = 1;
pdschDMRS.CustomSymbolSet = [];
pdschDMRS.DMRSPortSet = [];
pdschDMRS.NIDNSCID = [];
pdschDMRS.NSCID = 0;
pdschDMRS.NumCDMGroupsWithoutData = 2;
pdschDMRS.DMRSDownlinkR16 = false;
pdschDMRS.DMRSEnhancedR18 = false;

pdsch.DMRS = pdschDMRS;

% PDSCH PT-RS
pdschPTRS = nrPDSCHPTRSConfig;
pdschPTRS.TimeDensity = 1;
pdschPTRS.FrequencyDensity = 2;
pdschPTRS.REOffset = '00';
pdschPTRS.PTRSPortSet = [];

pdsch.PTRS = pdschPTRS;

cfgDL.PDSCH = {pdsch};

%% CSI-RS Instances Configuration
csirs = nrWavegenCSIRSConfig;
csirs.Enable = false;
csirs.Label = 'CSIRS1';
csirs.Power = 0;
csirs.BandwidthPartID = 1;
csirs.CSIRSType = 'nzp';
csirs.CSIRSPeriod = 'on';
csirs.RowNumber = 3;
csirs.Density = 'one';
csirs.SymbolLocations = 0;
csirs.SubcarrierLocations = 0;
csirs.NumRB = 52;
csirs.RBOffset = 0;
csirs.NID = 0;

cfgDL.CSIRS = {csirs};

% Generation
[nr_waveform,info] = nrWaveformGenerator(cfgDL);

Fs = info.ResourceGrids(1).Info.SampleRate; 								 % Specify the sample rate of the waveform in Hz

%% Impairments
% Memoryless cubic nonlinearity
nonlin = comm.MemorylessNonlinearity(	'LinearGain', 		0, ...
    'IIP3', 					30, ...
    'AMPMConversion', 10);
nr_waveform = nonlin(complex(nr_waveform));

% IQ imbalance
nr_waveform = iqimbal(nr_waveform, 8, (180/pi)*pi/5);

% Frequency offset
freqOff = comm.PhaseFrequencyOffset('FrequencyOffset', 10, ...
    'SampleRate', 		Fs);
nr_waveform = freqOff(nr_waveform);

% Phase noise
phaseNoise = comm.PhaseNoise('FrequencyOffset', [12288000 24576000], ...
    'Level', 					[-60 -80], ...
    'SampleRate', 			Fs);
nr_waveform = phaseNoise(nr_waveform);

% Phase offset
nr_waveform = nr_waveform * exp(1i*pi/8);

% DC offset
nr_waveform = nr_waveform + 0.1+0.2i;

% AWGN
nr_waveform = awgn(nr_waveform, 20, 'measured');

%% Visualize

% Time Scope
% timeScope = timescope('SampleRate', Fs, ...
%     'TimeSpanOverrunAction', 'scroll', ...
%     'TimeSpanSource', 'property', ...
%     'TimeSpan', 3.75e-06);
% timeScope(nr_waveform);
% release(timeScope);

%% Table
signal = nr_waveform;

% Parça boyutu
chunk_size = (length(signal)/100);

% Parça sayısı
num_chunks = floor(length(signal) / chunk_size);

% Sonuçları saklamak için tablolar
real_stats = zeros(num_chunks, 8); % Gerçek kısım istatistikleri
imag_stats = zeros(num_chunks, 8); % Sanal kısım istatistikleri
chunk_indices = (1:num_chunks)'; % Her parçanın indisi

% Parça bazlı hesaplamalar
for i = 1:num_chunks
    % Şu anki parçanın başlangıç ve bitiş indeksleri
    start_idx = (i - 1) * chunk_size + 1;
    end_idx = start_idx + chunk_size - 1;

    % Şu anki parça
    chunk = signal(start_idx:end_idx);

    % Gerçek ve sanal kısımlar
    real_part = real(chunk);
    imag_part = imag(chunk);

    % Gerçek kısım istatistikleri
    real_stats(i, 1) = min(real_part);
    real_stats(i, 2) = max(real_part);
    real_stats(i, 3) = mean(real_part);
    real_stats(i, 4) = median(real_part);
    real_stats(i, 5) = max(real_part) - min(real_part); % Peak-to-peak
    real_stats(i, 6) = rms(real_part); % RMS
    real_stats(i, 7) = std(real_part);
    real_stats(i, 8) = var(real_part);
    
    
    % Sanal kısım istatistikleri
    imag_stats(i, 1) = min(imag_part);
    imag_stats(i, 2) = max(imag_part);
    imag_stats(i, 3) = mean(imag_part);
    imag_stats(i, 4) = median(imag_part);
    imag_stats(i, 5) = max(imag_part) - min(imag_part); % Peak-to-peak
    imag_stats(i, 6) = rms(imag_part); % RMS
    imag_stats(i, 7) = std(imag_part);
    imag_stats(i, 8) = var(imag_part);
end

category = repmat({'nr'}, num_chunks, 1);

% Sonuçları tabloya koyma
real_stats_table_nr = array2table(real_stats, 'VariableNames', ...
    {'Min', 'Max', 'Mean', 'Median', 'PeakToPeak', 'RMS', 'Std', 'Var'});
real_stats_table_nr.Type = category; % Kategori sütununu ekle

imag_stats_table_nr = array2table(imag_stats, 'VariableNames', ...
    {'Min', 'Max', 'Mean', 'Median', 'PeakToPeak', 'RMS', 'Std', 'Var'});

imag_stats_table_nr.Type = category; % Kategori sütununu ekle
