% Generated by MATLAB(R) 24.2 (R2024b) and WLAN Toolbox 24.2 (R2024b).
% Generated on: 06-Dec-2024 16:51:36

%% Generating 802.11a/g/j (OFDM) waveform
% 802.11a/g/j (OFDM) configuration
nonHTCfg = wlanNonHTConfig('Modulation', 'OFDM', ...
    'ChannelBandwidth', 'CBW20', ...
    'MCS', 0, ...
    'PSDULength', 1000);

numPackets = 1;
% input bit source:
in = randi([0, 1], 1000, 1);


% Generation
wlan_waveform = wlanWaveformGenerator(in, nonHTCfg, ...
    'NumPackets', numPackets, ...
    'IdleTime', 0, ...
    'OversamplingFactor', 1, ...
    'ScramblerInitialization', 93, ...
    'WindowTransitionTime', 1e-07);

Fs = wlanSampleRate(nonHTCfg, 'OversamplingFactor', 1);  % Specify the sample rate of the waveform in Hz
%% Impairments
% AWGN
% wlan_waveform = awgn(wlan_waveform, 20, 'measured');
freqOff = comm.PhaseFrequencyOffset('FrequencyOffset',0, ...
    'SampleRate', 		Fs);
wlan_waveform = freqOff(wlan_waveform);

% %% Visualize
% % Spectrum Analyzer
% spectrum = spectrumAnalyzer('SampleRate', Fs);
% spectrum(wlan_waveform);
% release(spectrum);

%% Table
signal = wlan_waveform;

% Parça boyutu
chunk_size = (length(signal)/100);

% Parça sayısı
num_chunks = floor(length(signal) / chunk_size);

% Sonuçları saklamak için tablolar
real_stats = zeros(num_chunks, 8); % Gerçek kısım istatistikleri
imag_stats = zeros(num_chunks, 8); % Sanal kısım istatistikleri
chunk_indices = (1:num_chunks)'; % Her parçanın indisi

% Parça bazlı hesaplamalar
for i = 1:num_chunks
    % Şu anki parçanın başlangıç ve bitiş indeksleri
    start_idx = (i - 1) * chunk_size + 1;
    end_idx = start_idx + chunk_size - 1;

    % Şu anki parça
    chunk = signal(start_idx:end_idx);

    % Gerçek ve sanal kısımlar
    real_part = real(chunk);
    imag_part = imag(chunk);

    % Gerçek kısım istatistikleri
    real_stats(i, 1) = min(real_part);
    real_stats(i, 2) = max(real_part);
    real_stats(i, 3) = mean(real_part);
    real_stats(i, 4) = median(real_part);
    real_stats(i, 5) = max(real_part) - min(real_part); % Peak-to-peak
    real_stats(i, 6) = rms(real_part); % RMS
    real_stats(i, 7) = std(real_part);
    real_stats(i, 8) = var(real_part);
    
    
    % Sanal kısım istatistikleri
    imag_stats(i, 1) = min(imag_part);
    imag_stats(i, 2) = max(imag_part);
    imag_stats(i, 3) = mean(imag_part);
    imag_stats(i, 4) = median(imag_part);
    imag_stats(i, 5) = max(imag_part) - min(imag_part); % Peak-to-peak
    imag_stats(i, 6) = rms(imag_part); % RMS
    imag_stats(i, 7) = std(imag_part);
    imag_stats(i, 8) = var(imag_part);
end

category = repmat({'wlan'}, num_chunks, 1);

% Sonuçları tabloya koyma
real_stats_table_wlan = array2table(real_stats, 'VariableNames', ...
    {'Min', 'Max', 'Mean', 'Median', 'PeakToPeak', 'RMS', 'Std', 'Var'});
real_stats_table_wlan.Type = category; % Kategori sütununu ekle

imag_stats_table_wlan = array2table(imag_stats, 'VariableNames', ...
    {'Min', 'Max', 'Mean', 'Median', 'PeakToPeak', 'RMS', 'Std', 'Var'});

imag_stats_table_wlan.Type = category; % Kategori sütununu ekle

